<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SINDIYA-DIPIN" ignored="0" name="Retry-Fail-Cases" tests="5" failures="1" timestamp="2020-07-05T12:25:42 IST" time="0.066" errors="0">
  <testcase name="fail" time="0.012" classname="testng.practice.RetryTests">
    <skipped/>
  </testcase> <!-- fail -->
  <testcase name="fail" time="0.001" classname="testng.practice.RetryTests">
    <skipped/>
  </testcase> <!-- fail -->
  <testcase name="fail" time="0.001" classname="testng.practice.RetryTests">
    <skipped/>
  </testcase> <!-- fail -->
  <testcase name="fail" time="0.001" classname="testng.practice.RetryTests">
    <failure type="java.lang.AssertionError" message="WRONG!">
      <![CDATA[java.lang.AssertionError: WRONG!
at testng.practice.RetryTests.fail(RetryTests.java:12)
at java.util.ArrayList.forEach(ArrayList.java:1249)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- fail -->
  <testcase name="fail2" time="0.002" classname="testng.practice.RetryTests"/>
</testsuite> <!-- Retry-Fail-Cases -->
